# Generated by Django 3.1 on 2020-09-23 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200917_0700'),
        ('patient', '0002_auto_20200921_0754'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Patient_Health',
            new_name='Health_Status',
        ),
    ]
