# Generated by Django 3.1 on 2020-09-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='staff_email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
    ]
