# Generated by Django 3.1 on 2020-09-14 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200914_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='occupation',
            field=models.CharField(choices=[('D', 'Doctor'), ('N', 'Nurse')], default='D', max_length=20),
        ),
    ]
