# Generated by Django 3.1 on 2020-09-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200914_0459'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
    ]
