# Generated by Django 3.1 on 2020-09-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_patient_is_validated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='room_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
