# Generated by Django 3.1 on 2020-09-01 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200901_1045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'permissions': [('patient_access', 'Access for Patients')]},
        ),
    ]
