# Generated by Django 3.1.3 on 2020-11-05 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription_entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication', models.CharField(max_length=50)),
                ('instruction', models.TextField(max_length=200)),
                ('date', models.DateField(auto_now=True)),
                ('all_patient', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.all_patient')),
                ('patient', models.ForeignKey(default=1, limit_choices_to={'is_validated': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.patient')),
                ('staff', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.all_staff')),
            ],
        ),
        migrations.CreateModel(
            name='MedHistory_entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=50)),
                ('details', models.TextField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('all_patient', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.all_patient')),
                ('patient', models.ForeignKey(default=1, limit_choices_to={'is_validated': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.patient')),
                ('staff', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.all_staff')),
            ],
        ),
        migrations.CreateModel(
            name='Bill_entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=50)),
                ('details', models.TextField(max_length=200)),
                ('charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('all_patient', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.all_patient')),
                ('patient', models.ForeignKey(default=1, limit_choices_to={'is_validated': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.patient')),
                ('staff', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.all_staff')),
            ],
        ),
    ]
