# Generated by Django 3.1 on 2020-09-14 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200914_0459'),
        ('EHR', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill_entry',
            name='all_patient',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.all_patient'),
        ),
        migrations.AddField(
            model_name='medhistory_entry',
            name='all_patient',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.all_patient'),
        ),
        migrations.AddField(
            model_name='prescription_entry',
            name='all_patient',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.all_patient'),
        ),
        migrations.AlterField(
            model_name='bill_entry',
            name='patient',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.patient'),
        ),
        migrations.AlterField(
            model_name='medhistory_entry',
            name='patient',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.patient'),
        ),
        migrations.AlterField(
            model_name='prescription_entry',
            name='patient',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.patient'),
        ),
    ]
